name: Input Github Actions
on:
  workflow_dispatch:
    inputs:
      Code version:
        description: Choose the code version
        options:
          - One
          - Two
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Display the chosen input
        run: echo "Chosen value is ${{ github.event.inputs.code version }} "
