name: Input Github Actions
on:
  workflow_dispatch:
    inputs:
      CodeVersion:
        description: Choose the code version
        type: choice
        options:
          - One
          - Two
jobs:
  InputCheck:
      runs-on: ubuntu-latest
      steps:
        - name: Display the chosen input
          run: echo "Chosen value is ${{ github.event.inputs.CodeVersion }}"
        - name: Check Lowercase
          run: |
             echo "REPO="Hi,," >>${GITHUB_ENV}
             echo "The value of REPO is: ${REPO}"
