name: Input Github Actions
on:
  workflow_dispatch:
    inputs:
      CodeVersion:
        description: Choose the code version
        type: choice
        options:
          - One
          - Two
jobs:
  InputCheck:
      runs-on: ubuntu-latest
      steps:
        - name: Display the chosen input
          run: |
           VAR="Chosen value is ${{ github.event.inputs.CodeVersion }}"
           VAR_LC=${VAR,,}
           echo ${VAR_LC}
          
