on:
 workflow_dispatch
jobs:
  TestSparse:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/checkout@v3
        with:
          repository: DhevanandhThanikachalam/GitHubActionsDemo
          ref: main
          path: TestDownload
          sparse-checkout: |
            Test1
      - name: List folders
        run: ls -la TestDownload

