name: SampleAction 

on:
 workflow_dispatch
jobs:
  TestSparse:
    runs-on: ubuntu-latest
    steps:
      - name: TestSparse
        uses: actions/checkout@v3
        with:
          repository: DhevanandhThanikachalam/GitHubActionsDemo
          ref: main
          path: TestDownload
      - name: List folders
        run: ls -la TestDownload

