name: Check yq
on:
  workflow_dispatch:

jobs:
  yqCheck:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Display the yml content
          run: |
            yq r Env.yml
